### ISSUE TITLE
Simple optimisation

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#102]
Right now, we are faced with the problem of determining which bytecode instructions and structures need to be implemented and how. Therefore, we decided to pursue a simple optimization to understand the minimal transformation required to achieve this optimization.

The first possible optimization is illustrated in the following figure:
![IMAGE 2023-09-26 17:57:19](https://github.com/objectionary/jeo-maven-plugin/assets/51804353/1203f75b-df33-4236-b088-432977918ef2)

We need to implement that optimisation.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo my suggestion:
1. You're trying to covert bytecode to xmir according to the [paper](https://github.com/objectionary/reducing-programs-to-objects)
2. Relying on the xmir representation from the paper I'm trying to implement optimization that you described (working title - inlining)
3. When we both achieve some results - get back to the discussion of the specification

WDYT?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon I've already started the transformation according to the paper you linked. The problem is that we don't operate on source-level concepts like high-level statements and language constructs (assignments, flow control expressions, etc.) as the paper suggests. Put simply, the paper describes a source-to-source transformation, whereas we are dealing with a bytecode-to-source transformation. Thus, we can only operate on bytecode instructions, which makes it challenging to implement transformations as described in the paper (or perhaps even impossible).

Of course, we need to divide the work into two parts as originally planned. The key point to remember is that we operate at the bytecode level, not with high-level concepts. Therefore, we cannot rely solely on the paper. Instead, I suggest you depend on the results produced by the `jeo-maven-plugin`. If you need something specific that isn't present in the current implementation, just raise an issue in that repository, and I will implement what you need.

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look and let us know what you think

**Comment by yegor256** [comment]
@maxonfjvipon I agree with @volodya-lombrozo -- let's see the first result produced by this plugin and then we decide 1) how much we like it and 2) how much we need to modify the paper.

**Comment by volodya-lombrozo** [comment]
We have to transfer integration test for that issue from `jeo` repository to `opeo` repository: https://github.com/objectionary/opeo-maven-plugin/issues/6
Then we have to remove the integration test from this repostirory.
