### ISSUE TITLE
Generics IT test (fails)

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#188]
We have to write integration test that will convert Java bytecode with [generics](https://docs.oracle.com/javase/tutorial/java/generics/types.html) into EO and back to bytecode.  
The test should fail (no implementation needed yet).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#198](https://github.com/objectionary/jeo-maven-plugin/issues/198) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#198](https://github.com/objectionary/jeo-maven-plugin/issues/198) is solved here.
