### ISSUE TITLE
Takes IT test (fails)

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#189]
We have to write unit test that will use [Takes Framework](https://github.com/yegor256/takes) together with `jeo` and maybe simple optimization. The goal is to check that `jeo` doesn't break anything in real applications. For now test might fail, but we need to add puzzle or one more issue to fix this test in the future.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#202](https://github.com/objectionary/jeo-maven-plugin/issues/202) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#202](https://github.com/objectionary/jeo-maven-plugin/issues/202), [#292](https://github.com/objectionary/jeo-maven-plugin/issues/292) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 4 puzzles [#202](https://github.com/objectionary/jeo-maven-plugin/issues/202), [#292](https://github.com/objectionary/jeo-maven-plugin/issues/292), [#295](https://github.com/objectionary/jeo-maven-plugin/issues/295), [#296](https://github.com/objectionary/jeo-maven-plugin/issues/296) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#202](https://github.com/objectionary/jeo-maven-plugin/issues/202), [#292](https://github.com/objectionary/jeo-maven-plugin/issues/292) are still not solved; solved: [#295](https://github.com/objectionary/jeo-maven-plugin/issues/295), [#296](https://github.com/objectionary/jeo-maven-plugin/issues/296).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#202](https://github.com/objectionary/jeo-maven-plugin/issues/202), [#345](https://github.com/objectionary/jeo-maven-plugin/issues/345) are still not solved; solved: [#292](https://github.com/objectionary/jeo-maven-plugin/issues/292), [#295](https://github.com/objectionary/jeo-maven-plugin/issues/295), [#296](https://github.com/objectionary/jeo-maven-plugin/issues/296).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#202](https://github.com/objectionary/jeo-maven-plugin/issues/202) is still not solved; solved: [#292](https://github.com/objectionary/jeo-maven-plugin/issues/292), [#295](https://github.com/objectionary/jeo-maven-plugin/issues/295), [#296](https://github.com/objectionary/jeo-maven-plugin/issues/296), [#345](https://github.com/objectionary/jeo-maven-plugin/issues/345).
