### ISSUE TITLE
SNAPSHOT version in README.md

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#213]
At the moment, the `README.md` mentions `1.0.0-SNAPSHOT` version, which is not available in Maven Central. Thus, I can't use the example provided. I have to go to Maven Central and check what is the latest version. I suggest implementing this mechanism here: https://github.com/objectionary/eo/blob/master/.github/workflows/up.yml On every new release, it makes a pull request with a new version, into `README.md`

**Comment by volodya-lombrozo** [comment]
@yegor256 Thank you, we will definitely do it
