### ISSUE TITLE
EO files are not generated

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#215]
Would be great to generate not only `.xmir`, but also `.eo` file, into `target/generated-sources/eo`. This will help debug the tool, seeing what it generates. We can use this printer: https://github.com/objectionary/eo/blob/master/eo-parser/src/main/java/org/eolang/parser/XMIR.java

**Comment by volodya-lombrozo** [comment]
@yegor256 Yes, it would be great. Thank you!

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#221](https://github.com/objectionary/jeo-maven-plugin/issues/221) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#397](https://github.com/objectionary/jeo-maven-plugin/issues/397) is still not solved; solved: [#221](https://github.com/objectionary/jeo-maven-plugin/issues/221).

**Comment by 0pdd** [comment]
@yegor256 all 2 puzzles are solved here: [#221](https://github.com/objectionary/jeo-maven-plugin/issues/221), [#397](https://github.com/objectionary/jeo-maven-plugin/issues/397).
