### ISSUE TITLE
Integration Test With Auto Generated Java Code

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#218]
Currently `jeo` can't translate most of Java features. In order to increase the number of supported features we can add integration test that will do:

1. Generate random Java code (this code should be valid and compilable)
2. Run `jeo` on this code
3. Check that `jeo` successfully converted all Java classes into valid `xmir`

In order to implement this we have to find the tools available generate java code.

**Comment by volodya-lombrozo** [comment]
https://github.com/square/javapoet might help here

**Comment by volodya-lombrozo** [comment]
Asked related question: https://softwarerecs.stackexchange.com/questions/88232/generating-random-java-code

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#305](https://github.com/objectionary/jeo-maven-plugin/issues/305) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo all 2 puzzles are solved here: [#305](https://github.com/objectionary/jeo-maven-plugin/issues/305), [#313](https://github.com/objectionary/jeo-maven-plugin/issues/313).
