### ISSUE TITLE
Decompile primitive bytecode

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#260]
It is the part of #259 issue.

The first attempt to just parse bytecode didn't give anything useful for the further optimizations, so we decided to try to decompile `bytecode` into `eo` in order to get more high-level representation of a program.

To start, we have to decompile the simplest example:
```
public class Application{
public static void main(String... args){
  new B(new A(42)).bar();
}
}
``` 
into something like:
```eo
(b (a 42).new).new.bar
```

PS. I create this issue in order to keep #259 issue open.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#265](https://github.com/objectionary/jeo-maven-plugin/issues/265) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#265](https://github.com/objectionary/jeo-maven-plugin/issues/265) is solved here.
