### ISSUE TITLE
bytecode-to-eo doesn't print any logs

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#269]
The `bytecode-to-eo` goal doesn't print any logs. Would be great to see a log line per each file transpiled from bytecode to EO.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#279](https://github.com/objectionary/jeo-maven-plugin/issues/279) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#279](https://github.com/objectionary/jeo-maven-plugin/issues/279) is solved here.
