### ISSUE TITLE
remove opcode semantic information from their names

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#275]
Currently, I see this:

```
opcode > NEW-187-16
  "foo/Foo"
opcode > DUP-89-17
opcode > BIPUSH-16-18
  42
```

Instead, should be this:

```
opcode
  "NEW"
  "187"
  "16"
  "foo/Foo"
opcode
  "DUP"
  "89"
  "17"
opcode
  "BIPUSH"
  "16"
  "18"
  42
```

**Comment by volodya-lombrozo** [comment]
Current implementation use names **only** for debugging purposes and doesn't use this information in compilation/decompilation. All the required information passed as an object arguments (like on your code snippet).
