### ISSUE TITLE
JavaSourceCompilationIT.java:52-58: Add debug information...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/jeo-maven-plugin#313]
The puzzle `218-c31b689a` from #218 has to be resolved: 

https://github.com/objectionary/jeo-maven-plugin/blob/755f57a89423b447e9c66e3dd822112bdbcdf770/src/test/java/it/JavaSourceCompilationIT.java#L52-L58

The puzzle was created by rultor on 04-Dec-23. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
Most probably, we can close this issue, but the check is needed
