### ISSUE TITLE
Integration test for the entire optimization pipeline

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#34]
The pipeline should be the next:
1. Create simple java program (aka "Hello World")
2. Compile this program and get required class files
3. Start optimization mojo
4. Check that we have: 1) xmir representation of our bytecode 2) The class file of the program was changed after optimisation (modification time changed)
5. Run the program and see "Hello World" in the console.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#36](https://github.com/objectionary/jeo-maven-plugin/issues/36), [#37](https://github.com/objectionary/jeo-maven-plugin/issues/37) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#37](https://github.com/objectionary/jeo-maven-plugin/issues/37), [#39](https://github.com/objectionary/jeo-maven-plugin/issues/39), [#41](https://github.com/objectionary/jeo-maven-plugin/issues/41) are still not solved; solved: [#36](https://github.com/objectionary/jeo-maven-plugin/issues/36).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#37](https://github.com/objectionary/jeo-maven-plugin/issues/37), [#39](https://github.com/objectionary/jeo-maven-plugin/issues/39) are still not solved; solved: [#36](https://github.com/objectionary/jeo-maven-plugin/issues/36), [#41](https://github.com/objectionary/jeo-maven-plugin/issues/41).

**Comment by 0pdd** [comment]
@volodya-lombrozo 4 puzzles [#37](https://github.com/objectionary/jeo-maven-plugin/issues/37), [#48](https://github.com/objectionary/jeo-maven-plugin/issues/48), [#49](https://github.com/objectionary/jeo-maven-plugin/issues/49), [#50](https://github.com/objectionary/jeo-maven-plugin/issues/50) are still not solved; solved: [#36](https://github.com/objectionary/jeo-maven-plugin/issues/36), [#39](https://github.com/objectionary/jeo-maven-plugin/issues/39), [#41](https://github.com/objectionary/jeo-maven-plugin/issues/41).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#37](https://github.com/objectionary/jeo-maven-plugin/issues/37), [#48](https://github.com/objectionary/jeo-maven-plugin/issues/48), [#49](https://github.com/objectionary/jeo-maven-plugin/issues/49) are still not solved; solved: [#36](https://github.com/objectionary/jeo-maven-plugin/issues/36), [#39](https://github.com/objectionary/jeo-maven-plugin/issues/39), [#41](https://github.com/objectionary/jeo-maven-plugin/issues/41), [#50](https://github.com/objectionary/jeo-maven-plugin/issues/50).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#37](https://github.com/objectionary/jeo-maven-plugin/issues/37), [#53](https://github.com/objectionary/jeo-maven-plugin/issues/53) are still not solved; solved: [#36](https://github.com/objectionary/jeo-maven-plugin/issues/36), [#39](https://github.com/objectionary/jeo-maven-plugin/issues/39), [#41](https://github.com/objectionary/jeo-maven-plugin/issues/41), [#48](https://github.com/objectionary/jeo-maven-plugin/issues/48), [#49](https://github.com/objectionary/jeo-maven-plugin/issues/49), [#50](https://github.com/objectionary/jeo-maven-plugin/issues/50).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#55](https://github.com/objectionary/jeo-maven-plugin/issues/55), [#57](https://github.com/objectionary/jeo-maven-plugin/issues/57) are still not solved; solved: [#36](https://github.com/objectionary/jeo-maven-plugin/issues/36), [#37](https://github.com/objectionary/jeo-maven-plugin/issues/37), [#39](https://github.com/objectionary/jeo-maven-plugin/issues/39), [#41](https://github.com/objectionary/jeo-maven-plugin/issues/41), [#48](https://github.com/objectionary/jeo-maven-plugin/issues/48), [#49](https://github.com/objectionary/jeo-maven-plugin/issues/49), [#50](https://github.com/objectionary/jeo-maven-plugin/issues/50), [#53](https://github.com/objectionary/jeo-maven-plugin/issues/53).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#55](https://github.com/objectionary/jeo-maven-plugin/issues/55), [#76](https://github.com/objectionary/jeo-maven-plugin/issues/76) are still not solved; solved: [#36](https://github.com/objectionary/jeo-maven-plugin/issues/36), [#37](https://github.com/objectionary/jeo-maven-plugin/issues/37), [#39](https://github.com/objectionary/jeo-maven-plugin/issues/39), [#41](https://github.com/objectionary/jeo-maven-plugin/issues/41), [#48](https://github.com/objectionary/jeo-maven-plugin/issues/48), [#49](https://github.com/objectionary/jeo-maven-plugin/issues/49), [#50](https://github.com/objectionary/jeo-maven-plugin/issues/50), [#53](https://github.com/objectionary/jeo-maven-plugin/issues/53), [#57](https://github.com/objectionary/jeo-maven-plugin/issues/57).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#55](https://github.com/objectionary/jeo-maven-plugin/issues/55) is still not solved; solved: [#36](https://github.com/objectionary/jeo-maven-plugin/issues/36), [#37](https://github.com/objectionary/jeo-maven-plugin/issues/37), [#39](https://github.com/objectionary/jeo-maven-plugin/issues/39), [#41](https://github.com/objectionary/jeo-maven-plugin/issues/41), [#48](https://github.com/objectionary/jeo-maven-plugin/issues/48), [#49](https://github.com/objectionary/jeo-maven-plugin/issues/49), [#50](https://github.com/objectionary/jeo-maven-plugin/issues/50), [#53](https://github.com/objectionary/jeo-maven-plugin/issues/53), [#57](https://github.com/objectionary/jeo-maven-plugin/issues/57), [#76](https://github.com/objectionary/jeo-maven-plugin/issues/76).

**Comment by 0pdd** [comment]
@volodya-lombrozo all 11 puzzles are solved here: [#36](https://github.com/objectionary/jeo-maven-plugin/issues/36), [#37](https://github.com/objectionary/jeo-maven-plugin/issues/37), [#39](https://github.com/objectionary/jeo-maven-plugin/issues/39), [#41](https://github.com/objectionary/jeo-maven-plugin/issues/41), [#48](https://github.com/objectionary/jeo-maven-plugin/issues/48), [#49](https://github.com/objectionary/jeo-maven-plugin/issues/49), [#50](https://github.com/objectionary/jeo-maven-plugin/issues/50), [#53](https://github.com/objectionary/jeo-maven-plugin/issues/53), [#55](https://github.com/objectionary/jeo-maven-plugin/issues/55), [#57](https://github.com/objectionary/jeo-maven-plugin/issues/57), [#76](https://github.com/objectionary/jeo-maven-plugin/issues/76).
