### ISSUE TITLE
Provide an ability to change each method and constructor instructions

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#350]
Currently classes `XmlProgram`, `XmlClass`, `XmlMethod` are created from `Node` only. In case to copy or change them, we have to use `Directives*` classes which is extremely tedious. It would be nice to have useful constructors or methods that we can use in order to recreate, copy or change the content of `XmlProgram`, `XmlClass`, `XmlMethod`.

The original use case is to change any instructions in `XmlMethod`. For example, `opeo` plugin is trying to decompile some of the instructions and tries to insert results inside `XmlMethod`.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#352](https://github.com/objectionary/jeo-maven-plugin/issues/352) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#352](https://github.com/objectionary/jeo-maven-plugin/issues/352) is solved here.
