### ISSUE TITLE
site is not generated and not published for this Maven plugin

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#357]
Let's generate and publish it automatically

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#359](https://github.com/objectionary/jeo-maven-plugin/issues/359) is still not solved.

**Comment by yegor256** [comment]
@volodya-lombrozo once you release a new version of the plugin, the site will be generated. Maybe it's worth releasing now, to check?

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#359](https://github.com/objectionary/jeo-maven-plugin/issues/359) is solved here.
