### ISSUE TITLE
site.xml:45-48: For some reason, the "plugin-info.html"...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/jeo-maven-plugin#359]
The puzzle `357-f1fb7c4b` from #357 has to be resolved: 

https://github.com/objectionary/jeo-maven-plugin/blob/413bae2ae9d0ecf45a8e677ccd84b480819c5365/src/site/site.xml#L45-L48

The puzzle was created by Yegor Bugayenko on 21-Dec-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `357-f1fb7c4b` has disappeared from the source code, that's why I closed this issue.

**Comment by yegor256** [comment]
@volodya-lombrozo works fine now: https://www.objectionary.com/jeo-maven-plugin/plugin-info.html
