### ISSUE TITLE
Logic of suffixes in opcode commands

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/jeo-maven-plugin#361]
Consider the example: https://github.com/objectionary/opeo-maven-plugin/blob/master/src/test/resources/packs/simple_objects.yaml

Constructor of `A.eo` has the next opcodes: ALOAD-22, INVOKESPECIAL-23, ALOAD-24, ILOAD-25, PUTFIELD-26, RETURN-27.
Constructor of `B.eo` has the next opcodes: ALOAD-D, INVOKESPECIAL-E, ALOAD-F, ALOAD-10, PUTFIELD-11, RETURN-12

What do suffixes in commands mean and how I should create them if I'm trying to make custom class?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Please, let me know if you have any more questions.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo no more questions here
