### ISSUE TITLE
What is `label` object for?

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/jeo-maven-plugin#366]
I tried to create my own integration test using `bytecode-to-eo` goal. Java code that I'm trying to convert:
```java
package com.example;

public class A {
    private int d;
    public A(int d) { this.d = d; }
    public int foo() { return this.d * 2; }
}
```
The part of EO code that I get:
```
  [] > j$foo
    1 > access
    "()I" > descriptor
    "" > signature
    * > exceptions
    seq > @
      tuple
        label
          "dbe5a680-4814-4b19-a8e6-15c3c2db3a83"
        opcode > ALOAD-13
          25
          0
```
Object `label` is used several times in the code. What's it for?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon labels serve as markers or references that indicate specific points in the code
1. They might mark the entry- and exit- points of a method for debugging purposes (as in your example)
2. They provide jump points in the code (you will see more labels if try to add `if`, `for` statements in the code)  
For example:
```
GOTO label "dbe5a680-4814-4b19-a8e6-15c3c2db3a83"
ALOAD 1  //skipped
label "dbe5a680-4814-4b19-a8e6-15c3c2db3a83"
RETURN
```
3. Also they might be used for Exception handling

And of course, it isn't a limited list of usages. Maybe I should add this description to a README? Would it be helpful to you?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo yeah, it would be helpful

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Maybe something else, except `opcode` and `label`?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo I would like to know how should I handle these labels if I want to create custom class (in xmir) so it would convert back to bytecode successfully
