### ISSUE TITLE
rename goals to decode/encode

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#387]
Instead of `bytecode-to-eo` and `eo-to-bytecode` I suggest using these names:

  * `decode` -- we turn byte**codes** into objects, thus _decoding_
  * `encode` -- we turn objects into byte**codes**, thus _encoding_

**Comment by volodya-lombrozo** [comment]
@yegor256 I like `decode`, `encode`. Let's change it. However, I have one more suggestion, what about `disassemble` and
`assemble` names? Actually it is [exactly](https://en.wikipedia.org/wiki/Disassembler) what we are doing here:
> A disassembler is a [computer program](https://en.wikipedia.org/wiki/Computer_program) that [translates](https://en.wikipedia.org/wiki/Translator_(computing)) [machine language](https://en.wikipedia.org/wiki/Machine_language) into [assembly language](https://en.wikipedia.org/wiki/Assembly_language)—the inverse operation to that of an [assembler](https://en.wikipedia.org/wiki/Assembly_language#Assembler).

So, if we put all together (with `opeo`), we got the following pipeline:

`disassemble` -> `decompile` -> magic -> `compile` -> `assemble`

About the difference between `assembler` and `compiler` you can read [here](https://stackoverflow.com/questions/24622856/java-decompiler-vs-java-disassembler#:~:text=The%20javap%20command%20disassembles%20one%20or%20more%20class%20files%20and,codes%20into%20java%20source%20code.)

**Comment by volodya-lombrozo** [comment]
> The traditional difference (from the C language world):
* Compiler: compiles a relatively high-level source code to assembly language
* Assembler: compiles assembly code to machine code

**Comment by yegor256** [comment]
@volodya-lombrozo yes, assemble/disassemble look good!
