### ISSUE TITLE
Disable Bytecode Verification

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#435]
I've faced with an important problem. If we generate classes on the fly, we have to add them to classpath. 

For example, it the problem arises in [benchmark](https://github.com/objectionary/benchmark). We create `BA.xmir` which later transform to `BA.class`.
Since some other classes also dependent on `BA.class`, they can throw exception during bytecode verification (since we don't add BA.class to classpath one the fly).

Hence, we have to disable bytecode checks for now, but later fix the problem and enable verification.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#437](https://github.com/objectionary/jeo-maven-plugin/issues/437) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#437](https://github.com/objectionary/jeo-maven-plugin/issues/437) is solved here.
