### ISSUE TITLE
Add fat jar transformation integration test

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#464]
We need to test the following scenario:

1. Get `spring`  integration test (or create something similar)
2. Instead of using dependencies, we have to download them as jars, unpack and place under `lib` or `classes` directory
3. Transform all the classes to eo and back
4. Run the application

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518).

**Comment by 0pdd** [comment]
@volodya-lombrozo 4 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518).

**Comment by 0pdd** [comment]
@volodya-lombrozo 5 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524).

**Comment by 0pdd** [comment]
@volodya-lombrozo 7 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524).

**Comment by 0pdd** [comment]
@volodya-lombrozo 7 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531).

**Comment by 0pdd** [comment]
@volodya-lombrozo 9 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531).

**Comment by 0pdd** [comment]
@volodya-lombrozo 9 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531).

**Comment by 0pdd** [comment]
@volodya-lombrozo 8 puzzles [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540) are still not solved; solved: [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531).

**Comment by 0pdd** [comment]
@volodya-lombrozo 8 puzzles [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540), [#543](https://github.com/objectionary/jeo-maven-plugin/issues/543) are still not solved; solved: [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531).

**Comment by 0pdd** [comment]
@volodya-lombrozo 10 puzzles [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540), [#543](https://github.com/objectionary/jeo-maven-plugin/issues/543), [#699](https://github.com/objectionary/jeo-maven-plugin/issues/699), [#700](https://github.com/objectionary/jeo-maven-plugin/issues/700), [#701](https://github.com/objectionary/jeo-maven-plugin/issues/701) are still not solved; solved: [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536).

**Comment by 0pdd** [comment]
@volodya-lombrozo 8 puzzles [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540), [#543](https://github.com/objectionary/jeo-maven-plugin/issues/543), [#699](https://github.com/objectionary/jeo-maven-plugin/issues/699) are still not solved; solved: [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#700](https://github.com/objectionary/jeo-maven-plugin/issues/700), [#701](https://github.com/objectionary/jeo-maven-plugin/issues/701).

**Comment by 0pdd** [comment]
@volodya-lombrozo 7 puzzles [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540), [#543](https://github.com/objectionary/jeo-maven-plugin/issues/543), [#699](https://github.com/objectionary/jeo-maven-plugin/issues/699) are still not solved; solved: [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#700](https://github.com/objectionary/jeo-maven-plugin/issues/700), [#701](https://github.com/objectionary/jeo-maven-plugin/issues/701).

**Comment by 0pdd** [comment]
@volodya-lombrozo 6 puzzles [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540), [#543](https://github.com/objectionary/jeo-maven-plugin/issues/543), [#699](https://github.com/objectionary/jeo-maven-plugin/issues/699) are still not solved; solved: [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#700](https://github.com/objectionary/jeo-maven-plugin/issues/700), [#701](https://github.com/objectionary/jeo-maven-plugin/issues/701).

**Comment by 0pdd** [comment]
@volodya-lombrozo 8 puzzles [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#543](https://github.com/objectionary/jeo-maven-plugin/issues/543), [#699](https://github.com/objectionary/jeo-maven-plugin/issues/699), [#750](https://github.com/objectionary/jeo-maven-plugin/issues/750), [#751](https://github.com/objectionary/jeo-maven-plugin/issues/751), [#752](https://github.com/objectionary/jeo-maven-plugin/issues/752) are still not solved; solved: [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540), [#700](https://github.com/objectionary/jeo-maven-plugin/issues/700), [#701](https://github.com/objectionary/jeo-maven-plugin/issues/701).

**Comment by 0pdd** [comment]
@volodya-lombrozo 6 puzzles [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#543](https://github.com/objectionary/jeo-maven-plugin/issues/543), [#699](https://github.com/objectionary/jeo-maven-plugin/issues/699), [#750](https://github.com/objectionary/jeo-maven-plugin/issues/750) are still not solved; solved: [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540), [#700](https://github.com/objectionary/jeo-maven-plugin/issues/700), [#701](https://github.com/objectionary/jeo-maven-plugin/issues/701), [#751](https://github.com/objectionary/jeo-maven-plugin/issues/751), [#752](https://github.com/objectionary/jeo-maven-plugin/issues/752).

**Comment by 0pdd** [comment]
@volodya-lombrozo 5 puzzles [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#543](https://github.com/objectionary/jeo-maven-plugin/issues/543), [#750](https://github.com/objectionary/jeo-maven-plugin/issues/750) are still not solved; solved: [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540), [#699](https://github.com/objectionary/jeo-maven-plugin/issues/699), [#700](https://github.com/objectionary/jeo-maven-plugin/issues/700), [#701](https://github.com/objectionary/jeo-maven-plugin/issues/701), [#751](https://github.com/objectionary/jeo-maven-plugin/issues/751), [#752](https://github.com/objectionary/jeo-maven-plugin/issues/752).

**Comment by 0pdd** [comment]
@volodya-lombrozo 4 puzzles [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#543](https://github.com/objectionary/jeo-maven-plugin/issues/543), [#750](https://github.com/objectionary/jeo-maven-plugin/issues/750) are still not solved; solved: [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540), [#699](https://github.com/objectionary/jeo-maven-plugin/issues/699), [#700](https://github.com/objectionary/jeo-maven-plugin/issues/700), [#701](https://github.com/objectionary/jeo-maven-plugin/issues/701), [#751](https://github.com/objectionary/jeo-maven-plugin/issues/751), [#752](https://github.com/objectionary/jeo-maven-plugin/issues/752).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#534](https://github.com/objectionary/jeo-maven-plugin/issues/534), [#537](https://github.com/objectionary/jeo-maven-plugin/issues/537), [#750](https://github.com/objectionary/jeo-maven-plugin/issues/750) are still not solved; solved: [#488](https://github.com/objectionary/jeo-maven-plugin/issues/488), [#506](https://github.com/objectionary/jeo-maven-plugin/issues/506), [#509](https://github.com/objectionary/jeo-maven-plugin/issues/509), [#515](https://github.com/objectionary/jeo-maven-plugin/issues/515), [#518](https://github.com/objectionary/jeo-maven-plugin/issues/518), [#520](https://github.com/objectionary/jeo-maven-plugin/issues/520), [#524](https://github.com/objectionary/jeo-maven-plugin/issues/524), [#526](https://github.com/objectionary/jeo-maven-plugin/issues/526), [#528](https://github.com/objectionary/jeo-maven-plugin/issues/528), [#531](https://github.com/objectionary/jeo-maven-plugin/issues/531), [#532](https://github.com/objectionary/jeo-maven-plugin/issues/532), [#536](https://github.com/objectionary/jeo-maven-plugin/issues/536), [#540](https://github.com/objectionary/jeo-maven-plugin/issues/540), [#543](https://github.com/objectionary/jeo-maven-plugin/issues/543), [#699](https://github.com/objectionary/jeo-maven-plugin/issues/699), [#700](https://github.com/objectionary/jeo-maven-plugin/issues/700), [#701](https://github.com/objectionary/jeo-maven-plugin/issues/701), [#751](https://github.com/objectionary/jeo-maven-plugin/issues/751), [#752](https://github.com/objectionary/jeo-maven-plugin/issues/752).
