### ISSUE TITLE
Extremely slow disassembling 

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#499]
`spring-fat` integration test takes a significant amount of time to run. Recently, it took me 42 minutes and 49 seconds to complete, which is unacceptable. Initial CPU profiling results suggest that most of the time was spent in the `AllLabels` class, particularly in the `AllLabels#uid()` method. Additionally, separate memory profiling has revealed high usage of `java.util.concurrent.ConcurrentHashMap$MapEntry`, which is also utilized within the `AllLabels` class.

It is imperative that we enhance the performance of this integration test; otherwise, implementing all the necessary features will prove to be challenging.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#501](https://github.com/objectionary/jeo-maven-plugin/issues/501) is solved here.
