### ISSUE TITLE
Puzzle support

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#5]
We have to add puzzles support to that project

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13) is still not solved; solved: [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo 4 puzzles [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26) are still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo 5 puzzles [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31) are still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo 5 puzzles [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33) are still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo 4 puzzles [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33), [#44](https://github.com/objectionary/jeo-maven-plugin/issues/44) are still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33), [#44](https://github.com/objectionary/jeo-maven-plugin/issues/44) are still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33), [#44](https://github.com/objectionary/jeo-maven-plugin/issues/44) are still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33) is still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#44](https://github.com/objectionary/jeo-maven-plugin/issues/44), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33), [#705](https://github.com/objectionary/jeo-maven-plugin/issues/705) are still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#44](https://github.com/objectionary/jeo-maven-plugin/issues/44), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33), [#724](https://github.com/objectionary/jeo-maven-plugin/issues/724) are still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#44](https://github.com/objectionary/jeo-maven-plugin/issues/44), [#705](https://github.com/objectionary/jeo-maven-plugin/issues/705), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33), [#724](https://github.com/objectionary/jeo-maven-plugin/issues/724), [#730](https://github.com/objectionary/jeo-maven-plugin/issues/730) are still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#44](https://github.com/objectionary/jeo-maven-plugin/issues/44), [#705](https://github.com/objectionary/jeo-maven-plugin/issues/705), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33), [#724](https://github.com/objectionary/jeo-maven-plugin/issues/724) are still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#44](https://github.com/objectionary/jeo-maven-plugin/issues/44), [#705](https://github.com/objectionary/jeo-maven-plugin/issues/705), [#730](https://github.com/objectionary/jeo-maven-plugin/issues/730), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33) is still not solved; solved: [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#44](https://github.com/objectionary/jeo-maven-plugin/issues/44), [#705](https://github.com/objectionary/jeo-maven-plugin/issues/705), [#724](https://github.com/objectionary/jeo-maven-plugin/issues/724), [#730](https://github.com/objectionary/jeo-maven-plugin/issues/730), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#1577](https://github.com/objectionary/jeo-maven-plugin/issues/1577) is still not solved; solved: [#1015](https://github.com/objectionary/jeo-maven-plugin/issues/1015), [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33), [#44](https://github.com/objectionary/jeo-maven-plugin/issues/44), [#705](https://github.com/objectionary/jeo-maven-plugin/issues/705), [#724](https://github.com/objectionary/jeo-maven-plugin/issues/724), [#730](https://github.com/objectionary/jeo-maven-plugin/issues/730), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).

**Comment by 0pdd** [comment]
@volodya-lombrozo all 15 puzzles are solved here: [#1015](https://github.com/objectionary/jeo-maven-plugin/issues/1015), [#13](https://github.com/objectionary/jeo-maven-plugin/issues/13), [#1577](https://github.com/objectionary/jeo-maven-plugin/issues/1577), [#23](https://github.com/objectionary/jeo-maven-plugin/issues/23), [#24](https://github.com/objectionary/jeo-maven-plugin/issues/24), [#25](https://github.com/objectionary/jeo-maven-plugin/issues/25), [#26](https://github.com/objectionary/jeo-maven-plugin/issues/26), [#30](https://github.com/objectionary/jeo-maven-plugin/issues/30), [#31](https://github.com/objectionary/jeo-maven-plugin/issues/31), [#33](https://github.com/objectionary/jeo-maven-plugin/issues/33), [#44](https://github.com/objectionary/jeo-maven-plugin/issues/44), [#705](https://github.com/objectionary/jeo-maven-plugin/issues/705), [#724](https://github.com/objectionary/jeo-maven-plugin/issues/724), [#730](https://github.com/objectionary/jeo-maven-plugin/issues/730), [#9](https://github.com/objectionary/jeo-maven-plugin/issues/9).
