### ISSUE TITLE
Add `http` support to the `spring-fat` integration test 

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#548]
The `spring-fat` integration test starts a simple Spring Application with a single bean and this bean prints some logs to the stdout. If stdout contains required logs, we can say that test passes successfully. You can read more about the integration test right [here](https://github.com/objectionary/jeo-maven-plugin/tree/master/src/it/spring-fat).

Now we want make this test more "realistic". It would be nice to add `http` support to the application. The possible scenario might be:

1. Start Spring Application with some HTTP server (Spring Web?)
2. Make one http request to this server
3. Check the response status and content

Of course, we need to make `jeo-maven-plugin:disassemble` and `jeo-maven-plugin:assemble` before running the testing script described above.

**Comment by h1alexbel** [comment]
@volodya-lombrozo can I take this issue?

**Comment by volodya-lombrozo** [comment]
@h1alexbel Sure, please, go ahead! Btw, I did something similar to this issue [here](https://github.com/objectionary/opeo-maven-plugin/tree/master/src/it/spring-fat). Hope it will help.
