### ISSUE TITLE
opcode naming is invalid (starts with a capital letter)

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#574]
I'm getting this:

```
seq > @
      *
        label
          "9456b178-9c9f-4b44-9657-dc689e32a312"
        opcode > ALOAD-1
          25
          0
        opcode > INVOKESPECIAL-2
          183
          "java/lang/Object"
          "<init>"
          "()V"
```

In EO, we can't have names like this: `ALOAD-1` or `INVOKESPECIAL-2`. The first letter must be small, maybe: `oALOAD-1` or `oINVOKESPECIAL-2`.

**Comment by yegor256** [comment]
@volodya-lombrozo please, check

**Comment by volodya-lombrozo** [comment]
This issue was solved here: https://github.com/objectionary/jeo-maven-plugin/issues/678
