### ISSUE TITLE
Implement mojo that will convert byecode to eo only

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#58]
We have to implement mojo that will convert bytecode into eo objects (as `XMIR`) only, without back transpiration. This mojo has to be configurable - we have to be able to choose maven phase for it. Don't forget about integration tests.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#63](https://github.com/objectionary/jeo-maven-plugin/issues/63), [#64](https://github.com/objectionary/jeo-maven-plugin/issues/64) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo all 2 puzzles are solved here: [#63](https://github.com/objectionary/jeo-maven-plugin/issues/63), [#64](https://github.com/objectionary/jeo-maven-plugin/issues/64).
