### ISSUE TITLE
Back transpilation. Implement mojo that will convert eo to bytecode only.

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#59]
We have to implement mojo that will convert eo (as `XMIR`) back to bytecode. This mojo has to be configurable - we have to be able to choose maven phase for it. Don't forget about integration tests and documentation.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#69](https://github.com/objectionary/jeo-maven-plugin/issues/69), [#70](https://github.com/objectionary/jeo-maven-plugin/issues/70) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#70](https://github.com/objectionary/jeo-maven-plugin/issues/70), [#74](https://github.com/objectionary/jeo-maven-plugin/issues/74) are still not solved; solved: [#69](https://github.com/objectionary/jeo-maven-plugin/issues/69).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#70](https://github.com/objectionary/jeo-maven-plugin/issues/70) is still not solved; solved: [#69](https://github.com/objectionary/jeo-maven-plugin/issues/69), [#74](https://github.com/objectionary/jeo-maven-plugin/issues/74).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#376](https://github.com/objectionary/jeo-maven-plugin/issues/376) is still not solved; solved: [#69](https://github.com/objectionary/jeo-maven-plugin/issues/69), [#70](https://github.com/objectionary/jeo-maven-plugin/issues/70), [#74](https://github.com/objectionary/jeo-maven-plugin/issues/74).

**Comment by 0pdd** [comment]
@volodya-lombrozo all 4 puzzles are solved here: [#376](https://github.com/objectionary/jeo-maven-plugin/issues/376), [#69](https://github.com/objectionary/jeo-maven-plugin/issues/69), [#70](https://github.com/objectionary/jeo-maven-plugin/issues/70), [#74](https://github.com/objectionary/jeo-maven-plugin/issues/74).
