### ISSUE TITLE
Parameter Level Annotations

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#596]
I was using `jeo-maven-plugin` in `oleo-maven-plugin`, particularly in `spring-fat` integration test, and the test failed because the following code were transformed incorrectly:
```java
@GetMapping("/factorial")
    public String factorial(
        @RequestParam(value = "rounds", defaultValue = "1") String prounds,
        @RequestParam(value = "value", defaultValue = "10") String pvalue
    ) {
       // some other code here
    }
``` 

After disassembly/assembly goals the code above looks like as follows (decompiled bytecode):
```java
@GetMapping({"/factorial"})
    public String factorial(String var1, String var2) {
        // some other code here
    }
```

As you can see, we lost parameter-level annotations.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#598](https://github.com/objectionary/jeo-maven-plugin/issues/598) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#598](https://github.com/objectionary/jeo-maven-plugin/issues/598) is solved here.
