### ISSUE TITLE
Does 'jeo-maven-plugin' have any plans to support Java 8?

### ISSUE THREAD

**Issue by guangwang126** [objectionary/jeo-maven-plugin#610]
Does 'jeo-maven-plugin' have any plans to support Java 8?

**Comment by volodya-lombrozo** [comment]
@guangwang126 We didn't think about it yet, but I think we can add it. I'll put it in the plan. Have you tried to run it on Java 8? If so, did you receive any errors?

**Comment by 0pdd** [comment]
@guangwang126 2 puzzles [#618](https://github.com/objectionary/jeo-maven-plugin/issues/618), [#619](https://github.com/objectionary/jeo-maven-plugin/issues/619) are still not solved.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.4.6`, title is `0.4.6`.

**Comment by 0pdd** [comment]
@guangwang126 the puzzle [#619](https://github.com/objectionary/jeo-maven-plugin/issues/619) is still not solved; solved: [#618](https://github.com/objectionary/jeo-maven-plugin/issues/618).

**Comment by 0pdd** [comment]
@guangwang126 all 2 puzzles are solved here: [#618](https://github.com/objectionary/jeo-maven-plugin/issues/618), [#619](https://github.com/objectionary/jeo-maven-plugin/issues/619).
