### ISSUE TITLE
Transform `jeo-maven-plugin` output to PHI expressions

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#627]
When we have two separate methods with the same name (method overloading), we can't transform it to EO.
EO requires all the object names to be unique.
Also we might have some different problems in PHI printing.
We should add EO printing to check that `jeo-maven-plugin` prints all the parts to PHI expressions successfully.

**Comment by 0pdd** [comment]
@volodya-lombrozo 5 puzzles [#633](https://github.com/objectionary/jeo-maven-plugin/issues/633), [#634](https://github.com/objectionary/jeo-maven-plugin/issues/634), [#635](https://github.com/objectionary/jeo-maven-plugin/issues/635), [#636](https://github.com/objectionary/jeo-maven-plugin/issues/636), [#637](https://github.com/objectionary/jeo-maven-plugin/issues/637) are still not solved.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.5.0`, title is `0.5.0`.

**Comment by 0pdd** [comment]
@volodya-lombrozo 4 puzzles [#633](https://github.com/objectionary/jeo-maven-plugin/issues/633), [#634](https://github.com/objectionary/jeo-maven-plugin/issues/634), [#635](https://github.com/objectionary/jeo-maven-plugin/issues/635), [#636](https://github.com/objectionary/jeo-maven-plugin/issues/636) are still not solved; solved: [#637](https://github.com/objectionary/jeo-maven-plugin/issues/637).

**Comment by 0pdd** [comment]
@volodya-lombrozo 4 puzzles [#633](https://github.com/objectionary/jeo-maven-plugin/issues/633), [#634](https://github.com/objectionary/jeo-maven-plugin/issues/634), [#635](https://github.com/objectionary/jeo-maven-plugin/issues/635), [#697](https://github.com/objectionary/jeo-maven-plugin/issues/697) are still not solved; solved: [#636](https://github.com/objectionary/jeo-maven-plugin/issues/636), [#637](https://github.com/objectionary/jeo-maven-plugin/issues/637).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#633](https://github.com/objectionary/jeo-maven-plugin/issues/633), [#634](https://github.com/objectionary/jeo-maven-plugin/issues/634), [#635](https://github.com/objectionary/jeo-maven-plugin/issues/635) are still not solved; solved: [#636](https://github.com/objectionary/jeo-maven-plugin/issues/636), [#637](https://github.com/objectionary/jeo-maven-plugin/issues/637), [#697](https://github.com/objectionary/jeo-maven-plugin/issues/697).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#633](https://github.com/objectionary/jeo-maven-plugin/issues/633), [#635](https://github.com/objectionary/jeo-maven-plugin/issues/635) are still not solved; solved: [#634](https://github.com/objectionary/jeo-maven-plugin/issues/634), [#636](https://github.com/objectionary/jeo-maven-plugin/issues/636), [#637](https://github.com/objectionary/jeo-maven-plugin/issues/637), [#697](https://github.com/objectionary/jeo-maven-plugin/issues/697).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#633](https://github.com/objectionary/jeo-maven-plugin/issues/633) is still not solved; solved: [#634](https://github.com/objectionary/jeo-maven-plugin/issues/634), [#635](https://github.com/objectionary/jeo-maven-plugin/issues/635), [#636](https://github.com/objectionary/jeo-maven-plugin/issues/636), [#637](https://github.com/objectionary/jeo-maven-plugin/issues/637), [#697](https://github.com/objectionary/jeo-maven-plugin/issues/697).
