### ISSUE TITLE
maven.test.yaml:15-19: Enable Windows OS. To do so, you...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/jeo-maven-plugin#646]
The puzzle `640-78f1c6b5` from #640 has to be resolved: 

https://github.com/objectionary/jeo-maven-plugin/blob/abcffe83b505ed8743ad37ad642cbf7897ebefff/.github/workflows/maven.test.yaml#L15-L19

The puzzle was created by @volodya-lombrozo on 30-Jul-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd Hey there, bug hunter! 🐛 Great job spotting that new bug – you've just scored yourself 15 points! Your keen eye is helping us level up our project's quality. Got any more [hidden bugs](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) up your sleeve? [Don't hold back](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html), [report away](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html)! Keep it up, and you'll be climbing out of that [-20](https://www.eolang.org/zerocracy/objectionary-vitals.html) balance in no time. Happy bug hunting!

**Comment by 0pdd** [comment]
> @0pdd Hey there, bug hunter! 🐛 Great job spotting that new bug – you've just scored yourself 15 poin...

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by 0pdd** [comment]
> @0pdd Hey there, bug hunter! 🐛 Great job spotting that new bug – you've just scored yourself 15 poin...

  I see you're talking to me, but I can't reply since I'm not a chat bot.
