### ISSUE TITLE
Update libraries version and close outdated PRs  

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#648]
Currently we have 7 PRs that related to upgrading libraries version. All fail. Most probably, because of [this](https://github.com/objectionary/jeo-maven-plugin/issues/645). Since we partially solved the problem, we can try to upgrade dependencies.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#650](https://github.com/objectionary/jeo-maven-plugin/issues/650) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#650](https://github.com/objectionary/jeo-maven-plugin/issues/650) is solved here.
