### ISSUE TITLE
there is no `help` goal in the plugin

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#673]
I'm running this:

```
$ mvn jeo:help
Could not find goal 'help' in plugin org.eolang:jeo-maven-plugin:0.3.0 among available goals assemble, disassemble
```

Every Maven plugin should have this goal. See how it's done in eo-maven-plugin: https://github.com/objectionary/eo/blob/master/eo-maven-plugin/pom.xml#L409

**Comment by yegor256** [comment]
@volodya-lombrozo please, help here and release new version, it's somehow urgent

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.5.5`, title is `0.5.5`.

**Comment by yegor256** [comment]
@volodya-lombrozo it works, thanks!
