### ISSUE TITLE
pom.xml:302-309: Enable phi-unphi integration test. The...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/jeo-maven-plugin#705]
The puzzle `30-5cf3cafc` from #30 has to be resolved: 

https://github.com/objectionary/jeo-maven-plugin/blob/1a612a2245363bb141a85f8b25ae6b40483d77a3/pom.xml#L302-L309

The puzzle was created by @volodya-lombrozo on 15-Sep-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `30-5cf3cafc` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#724](https://github.com/objectionary/jeo-maven-plugin/issues/724) is still not solved.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.0`, title is `0.6.0`.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#724](https://github.com/objectionary/jeo-maven-plugin/issues/724), [#730](https://github.com/objectionary/jeo-maven-plugin/issues/730) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#724](https://github.com/objectionary/jeo-maven-plugin/issues/724) is still not solved; solved: [#730](https://github.com/objectionary/jeo-maven-plugin/issues/730).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#724](https://github.com/objectionary/jeo-maven-plugin/issues/724), [#730](https://github.com/objectionary/jeo-maven-plugin/issues/730).
