### ISSUE TITLE
broken name of attribute (starts with a digit)

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#753]
I see this in the .phi file that JEO generates:

```
α2 ↦ ξ.2dedb735-e2aa-4514-a7ac-eb20dc70361a,
```

Here, the name of the attribute is invalid, since it starts with a digit (must be a letter).

**Comment by yegor256** [comment]
@volodya-lombrozo please, pay attention to this one, it's a blocker

**Comment by volodya-lombrozo** [comment]
@yegor256 Thank you for the bug report. I will attend to it shortly.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.1`, title is `0.6.1`.
