### ISSUE TITLE
`φTerm` as attribute name is invalid

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#769]
If this is my Java code:

```
class Foo {
  void φTerm() {
  }
}
```

Then I get this in XMIR after jeo:disassemble:

```
<o abstract="" name="φTerm-KClMamF2YS9sYW5nL1N0cmluZzs=">
...
```

This obviously is a wrong attribute name for XMIR.

**Comment by yegor256** [comment]
@volodya-lombrozo please, check

**Comment by volodya-lombrozo** [comment]
@yegor256 Can I check similar mistakes somehow during `XMIR` generation? Do you have any linters or something similar I can use?

**Comment by yegor256** [comment]
@volodya-lombrozo  not yet. Just make sure you have proper naming for the `<o name='...'` part: must start with `[a-z]` and may not have any special symbols inside (space, dot, dash, `@`, `>`, `:`)

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.8`, title is `0.6.8`

**Comment by volodya-lombrozo** [comment]
@yegor256 Can we close this issue then?

**Comment by yegor256** [comment]
@volodya-lombrozo this one is fixed, thanks!
