### ISSUE TITLE
`OpcodeName#code` for compatibility with opeo

### ISSUE THREAD

**Issue by h1alexbel** [objectionary/jeo-maven-plugin#770]
Currently, `org.eolang.jeo.representation.directives.OpcodeName` does not support `code()` method, which is used by 
[opeo](https://github.com/objectionary/opeo-maven-plugin) `org.eolang.opeo.ast.OpcodeName` inside `it/AgentsIT.java`. Let's add this method to `org.eolang.jeo.representation.directives.OpcodeName`in order to resolve https://github.com/objectionary/opeo-maven-plugin/issues/75

**Comment by h1alexbel** [comment]
@volodya-lombrozo WDYT?

**Comment by volodya-lombrozo** [comment]
@h1alexbel To be honest, I don't like this method because it looks like a getter. However, I understand, that without it we won't be able to remove this duplication. So, let's add it, but later I would remove this method.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.7`, title is `0.6.7`

**Comment by 0pdd** [comment]
@h1alexbel the only puzzle [#772](https://github.com/objectionary/jeo-maven-plugin/issues/772) is solved here.
