### ISSUE TITLE
package name with capital letter first leads to broken .xmir

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#779]
If my package name starts with a capital letter, I'm getting this:

```
   <metas>
      <meta>
         <head>package</head>
         <tail>EOorg.EOeolang</tail>
         <part>EOorg.EOeolang</part>
      </meta>
      ...
```

Here, `EOorg.EOeolang` is not a valid package name. Every part in the package name must be a valid attribute name, which must start with a small English letter. Probably, it should be something like:

```
   <metas>
      <meta>
         <head>package</head>
         <tail>j$EOorg.j$EOeolang</tail>
         <part>j$EOorg.j$EOeolang</part>
      </meta>
      ...

```

**Comment by yegor256** [comment]
@volodya-lombrozo please, help

**Comment by volodya-lombrozo** [comment]
@yegor256 Yes, sure, I will do it. However, the usage of capital letters in package names is [the dangerous practice](https://stackoverflow.com/questions/12534302/why-should-java-package-name-be-lowercase) and should be avoided:

> Package names are written in all lower case to avoid conflict with the names of classes or interfaces.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.9`, title is `0.6.9`

**Comment by yegor256** [comment]
@volodya-lombrozo thanks!
