### ISSUE TITLE
disassemble should skip if target file is newer than the source

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#784]
Currently, the `disassemble` goal processes all files, even though some of them may be skipped: when target file is newer than the source one. The same is true for the `assemble` goal.

**Comment by yegor256** [comment]
@volodya-lombrozo please, check this one

**Comment by volodya-lombrozo** [comment]
It might be a good optimization, indeed. Does this slowdown influence you build much?

**Comment by yegor256** [comment]
@volodya-lombrozo this is just a common practice in Maven: build incrementally, skipping duplicate builds. Of course, it will save some time (especially on large projects).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#869](https://github.com/objectionary/jeo-maven-plugin/issues/869) is still not solved.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.18`, title is `0.6.18`

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you try the new `0.6.18` version please? It should do last modification time checking.

**Comment by volodya-lombrozo** [comment]
@yegor256 Friendly reminder

**Comment by yegor256** [comment]
@volodya-lombrozo thanks!

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#869](https://github.com/objectionary/jeo-maven-plugin/issues/869) is solved here.
