### ISSUE TITLE
package name starts with a capital letter (CONTD.)

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#785]
This is my Java:

```
package EOorg.EOeolang;
public final class EOi16$EOdiv extends PhDefault {

```

This is the XMIR I'm getting after jeo disassemble:

```
   <metas>
      <meta>
         <head>package</head>
         <tail>j$EOorg.EOeolang</tail>
         <part>j$EOorg.EOeolang</part>
      </meta>
```

Again, the name of the package is wrong, it starts with `E`.

**Comment by yegor256** [comment]
@volodya-lombrozo please, check

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.10`, title is `0.6.10`

**Comment by volodya-lombrozo** [comment]
@yegor256 could you check the new version, please?

**Comment by yegor256** [comment]
@volodya-lombrozo this bug is gone, thanks!
