### ISSUE TITLE
Add one more integration test with JNA use 

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#824]
In order to fix this problem https://github.com/objectionary/hone-maven-plugin/issues/58 it's better to try to reproduce the problem in `jeo-maven-plugin`. We can create one more test with JNA usage for this purpose.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#1004](https://github.com/objectionary/jeo-maven-plugin/issues/1004) is still not solved; solved: [#829](https://github.com/objectionary/jeo-maven-plugin/issues/829), [#999](https://github.com/objectionary/jeo-maven-plugin/issues/999).

**Comment by 0pdd** [comment]
@volodya-lombrozo all 3 puzzles are solved here: [#1004](https://github.com/objectionary/jeo-maven-plugin/issues/1004), [#829](https://github.com/objectionary/jeo-maven-plugin/issues/829), [#999](https://github.com/objectionary/jeo-maven-plugin/issues/999).
