### ISSUE TITLE
Arguments can't fit into locals in class file `org/apache/tomcat/util/http/FastHttpDateFormat`

### ISSUE THREAD

**Issue by h1alexbel** [objectionary/jeo-maven-plugin#826]
First, I added these dependencies into `it/spring-fat/pom.xml`:

```xml
<dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
</dependencies>
```

I've used latest JEO version: `@project.version@`.

Then, I used [invoker](https://maven.apache.org/plugins/maven-invoker-plugin) to run the test:

```bash
mvn clean integration-test -Dinvoker.test=spring-fat -DskipTests -e
```

Which invokes these goals: `clean test -e`.

Both disassembling and assembling passes, but application failed to start Tomcat web server due to problems with class file (after `jeo-maven-plugin:assemble`): [test.log](https://github.com/user-attachments/files/17572728/test.log) (it's too big to paste it here)

I'm not sure, but probably `jeo-maven-plugin:assemble` goal fails to build valid class file for `org.apache.tomcat.util.http.FastHttpDateFormat` and `org.apache.tomcat.util.http.SocketWrapperBase`

**Comment by h1alexbel** [comment]
@volodya-lombrozo take a look, please

**Comment by volodya-lombrozo** [comment]
@h1alexbel It seem we have the problem related to the  `max_locals` value computation this time. Thank you for reporting the bug!

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.14`, title is `0.6.14`

**Comment by volodya-lombrozo** [comment]
@h1alexbel Would you mind trying the new `0.6.14` version, please? It should solve the problem.

**Comment by h1alexbel** [comment]
@volodya-lombrozo checked new version - it works now, thanks!
