### ISSUE TITLE
Base64 in attribute names makes reading almost impossible

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#844]
It's hard to read the XMIR produced by JEO (and then the `.phi` file), where names of attributes look like this:

```
annotation-781842313-TG9yZy9vcGVuamRrL2ptaC9hbm5vdGF0aW9ucy9CZW5jaG1hcmtNb2RlOw==
param-TGphdmEvbGFuZy9Mb25nOw==-0
j$lambda$static$0-KExqYXZhL2xhbmcvTG9uZzspTGphdmEvbGFuZy9TdHJpbmc7
α2 ↦ ξ.a2c2e242-ef94-4642-b87b-dc94e275070b
```

Maybe, it's possible to invent some other mechanism of names encryption, which would keep them XMIR-compiant and at the same time readable? Maybe just replace unacceptable chars with `%xx` (like [it's done](https://en.wikipedia.org/wiki/Percent-encoding) in URL encoding)?

**Comment by yegor256** [comment]
@volodya-lombrozo this is kind of a blocker, please check

**Comment by volodya-lombrozo** [comment]
@yegor256 Thank you for reporting the possible improvement. We will take a look soon what can be made.

**Comment by volodya-lombrozo** [comment]
@yegor256 could you try the new version please? It should solve all the recent small issues you created.
