### ISSUE TITLE
the `listing` XML element contains binary code

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#845]
Currently, if I understand correctly, the `<listing/>` element in the XMIR generated by JEO, contains Base64-encoded content of the `.class` file that was disassembled. This doesn't help much in comprehending the XMIR content. Would be much better if we can put there Java code disassembled by some Bytecode-to-Java disassembler, maybe this one: https://github.com/Storyyeller/Krakatau

Or maybe just [`javap`](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javap.html)?

**Comment by yegor256** [comment]
@volodya-lombrozo please, check

**Comment by volodya-lombrozo** [comment]
@yegor256 Of course, it's a good thing. I guess, we can add both options: 1) `javap` and 2) `decompiler`

**Comment by yegor256** [comment]
@volodya-lombrozo `javap` looks like the easiest solution at the moment, would be great to have it ASAP. Without it, it's very hard or almost impossible to deal with the XMIR -- I simply can't understand what does it represent.

**Comment by volodya-lombrozo** [comment]
@yegor256 This issue was solved in the recent release. Can we close it?
