### ISSUE TITLE
the `org.eolang.jeo` package name is a bit misleading

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#846]
Currently, the atoms from JEO are temporary and don't exist at objectionary/home. They are used only/mostly for disassemble/assemble pipeline. I suggest renaming the `org.eolang.jeo` package just to `jeo`:

```
org.eolang.jeo.opcode -> jeo.opcode
org.eolang.jeo.string -> jeo.string
org.eolang.jeo.label  -> jeo.label
```

This will help us read XMIR document better, avoiding confusion.

**Comment by yegor256** [comment]
@volodya-lombrozo please, check

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.16`, title is `0.6.16`

**Comment by yegor256** [comment]
@volodya-lombrozo it works, thanks
