### ISSUE TITLE
the `data` attribute is deprecated

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#850]
We don't have `data="bytes"` attribute in XMIR anymore, it's deprecated. You can easily remove it.

**Comment by yegor256** [comment]
@volodya-lombrozo check this one please

**Comment by volodya-lombrozo** [comment]
@yegor256 It's impossible. I tried to remove `@data` attribute from  `org.eolang.bytes` object and failed. When we do this, `eo-maven-plugin:xmir-to-phi` goal removes all the bytes from the object.

After disassembling (without `data` attribute):

```xml
<o base="jeo.int" line="1246658856" name="version">
   <o base="org.eolang.bytes">00 00 00 00 00 00 00 34</o>
</o>
```

Then, after `eo-maven-plugin:xmir-to-phi` goal:

```phi
version ↦ ξ.jeo.int(
  α0 ↦ Φ.org.eolang.bytes
),
```

As you can see, bytes are lost.

**Comment by volodya-lombrozo** [comment]
Blocked by https://github.com/objectionary/eo/issues/3494

**Comment by yegor256** [comment]
@yegor256 the https://github.com/objectionary/eo/issues/3494 is merged and released (0.42.0), you can proceed here

**Comment by volodya-lombrozo** [comment]
@yegor256 I can't. The issue is still blocked by https://github.com/objectionary/eo/issues/3494

**Comment by yegor256** [comment]
@volodya-lombrozo try version 0.43.0, should work

**Comment by volodya-lombrozo** [comment]
@yegor256 With `0.43.0` the previous issue is gone. Now we have a different blocker:
https://github.com/objectionary/eo/issues/3535

**Comment by volodya-lombrozo** [comment]
@yegor256 Blocked by https://github.com/objectionary/eo/issues/3534

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#909](https://github.com/objectionary/jeo-maven-plugin/issues/909) is still not solved.

**Comment by yegor256** [comment]
@volodya-lombrozo I believe, this one is fixed
