### ISSUE TITLE
The `@version` attribute is not set correction of the XMIR

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#898]
I'm using jeo 0.6.20, and I'm getting this XMIR:

```
<?xml version="1.0" encoding="UTF-8"?>
<program dob="2024-11-22T17:25:13.741113259Z"
         ms="1732296314430"
         name="j$Big"
         revision="0.0.0"
         time="2024-11-22T17:25:13.741113259Z"
         version="0.0.0">
[...]
```

What these `version="0.0.0"` means? I expect to see `version="0.6.20"` there. This `@version` attribute is the version of the generator of this XMIR. If it's JEO, here we should see the version of JEO.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.21`, title is `0.6.21`
