### ISSUE TITLE
the value of the `@ms` attribute looks weird

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#904]
I see this, after running the `disassemble` goal:

```
<program dob="2024-11-23T15:49:21"
         ms="1732412464051"
         name="j$Foo"
         revision="4767144"
         time="2024-11-24T01:41:03.900297837Z"
         version="0.6.21">
```

The value of the `@ms` attribute is supposed to be equal to the number or milliseconds spent on generating this XML document. The value I see is not that.

**Comment by yegor256** [comment]
@volodya-lombrozo please, check

**Comment by volodya-lombrozo** [comment]
@yegor256 I've added `ms` computation in the `0.6.22`

**Comment by yegor256** [comment]
@volodya-lombrozo thanks!
