### ISSUE TITLE
`seq*` must be from the `jeo` package

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#907]
Currently, I see this, for example: `org.eolang.seq6`. There is no such object in the `org.eolang` package. Instead, let's use `jeo` package.

Moreover, I suggest renaming them to `jeo.seq.of1`, `jeo.seq.of2`, `jeo.seq.of42`, etc. This will simplify phi rewriting rules. It will be possible to match by `jeo.seq.*`. Now I can't do this at all.

**Comment by yegor256** [comment]
@volodya-lombrozo please, check

**Comment by volodya-lombrozo** [comment]
@yegor256 This issue should be solved in the `0.6.22` version as well, can you check it, please?

**Comment by yegor256** [comment]
@volodya-lombrozo thanks!
