### ISSUE TITLE
upgrade to eo 0.43.2

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#908]
Try to upgrade to eo 0.43.2. In this version, we've made our XSD much stricter and more informative in terms of documentation. It's important to upgrade, to enable integration of this plugin into HONE.

**Comment by yegor256** [comment]
@volodya-lombrozo please, help

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.22`, title is `0.6.22`

**Comment by yegor256** [comment]
@volodya-lombrozo thanks, it kind of works, but there are bugs: https://github.com/objectionary/jeo-maven-plugin/issues/912
