### ISSUE TITLE
broken `<meta>` in the output XMIR

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#912]
I'm using jeo:disassemble 0.6.22 and I'm getting this XMIR:

```
<meta>
  <head>package</head>
  <tail/>
  <part/>
</meta>
```

This is not a valid XMIR, since `part` can't be empty. Moreover, why `tail` is empty? Full story is here: https://github.com/objectionary/hone-maven-plugin/pull/127

**Comment by yegor256** [comment]
@volodya-lombrozo please, help

**Comment by volodya-lombrozo** [comment]
@yegor256 Does your class has `package` declaration?

**Comment by volodya-lombrozo** [comment]
@yegor256 I've checked the test and you don't have a package declaration:

```java
.write("class Hello { double foo() { return Math.sin(42); } }".getBytes());
```

I guess you can add it and everything will work just fine:
```java
.write("package org.eolang.hone; \n class Hello { double foo() { return Math.sin(42); } }".getBytes());
```

**Comment by yegor256** [comment]
@volodya-lombrozo when package is not declared, don't put `package` meta in the XMIR. Very often we don't have packages, it's legal.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.23`, title is `0.6.23`

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you check the new version, please?

**Comment by yegor256** [comment]
@volodya-lombrozo this problem is gone, thanks!
