### ISSUE TITLE
it's better to use different atoms for different opcodes

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#917]
Currently, jeo:disassemble generates this phi (via XMIR):

```
φ ↦ Φ.jeo.seq.of6(
  α0 ↦ ξ.getstatic-25D7,
  α1 ↦ ξ.invokestatic-25E3,
  α2 ↦ ξ.invokedynamic-2600,
  α3 ↦ ξ.invokeinterface-2622,
  α4 ↦ ξ.invokeinterface-2627,
  α5 ↦ ξ.lreturn-2629
),

invokestatic-25E3 ↦ Φ.jeo.opcode( ... )

invokedynamic-2600 ↦ Φ.jeo.opcode( ... )
```

It's rather inconvenient for further processing. Instead, this would be better:

```
φ ↦ Φ.jeo.seq.of6(
  α0 ↦ ξ.a25D7,
  α1 ↦ ξ.a25E3,
  α2 ↦ ξ.a2600,
  α3 ↦ ξ.a2622,
  α4 ↦ ξ.a2627,
  α5 ↦ ξ.a2629
),

a25E3 ↦ Φ.jeo.opcode.invokestatic( ... )

a2600 ↦ Φ.jeo.opcode.invokedynamic( ... )
```

Possible?

**Comment by yegor256** [comment]
@volodya-lombrozo please, check

**Comment by yegor256** [comment]
@volodya-lombrozo actually, the name of the attribute (`getstatic-25D7`) doesn't matter at all, it may stay as is. What matters is the name of the atom/object being used (`jeo.opcode.invokestatic`).

**Comment by volodya-lombrozo** [comment]
@yegor256 I don't clearly understand these `phi` expressions and haven't found any documentation on it. Can you please explain what does this mean:

`α0 ↦ ξ.a25D7` - is it an object with `base=α0` and `name=a25D7`  or something else?
What is the difference between `Φ` and `ξ`?

As for the issue itself, simply saying, do you want instead of:

```xml
<o base="jeo.opcode" name="invokespecial-188">
...
</o>
```

have something like:

```xml
<o base="jeo.opcode.invokespecial" name="a188">
...
</o>
```
?

**Comment by yegor256** [comment]
@volodya-lombrozo yes, exactly

**Comment by volodya-lombrozo** [comment]
@yegor256 Instead of 1 atom, we will get 202 of them. It might complicate things significantly and increase coupling. Is it necessary? Moreover it will require significant changes in `opec-maven-plugin` if we decide to continue with it.

**Comment by yegor256** [comment]
@volodya-lombrozo 202 atoms is fine. Without this we technically can't write a rule for eo-phi-normalizer. We can't do this (assuming the `*` is a wildcard):

```
*-25E3 ↦ Φ.jeo.opcode( ... )
```

We can only do this:

```
* ↦ Φ.jeo.opcode.invokestatic( ... )
```

**Comment by volodya-lombrozo** [comment]
@yegor256 Well, ok, I will do it then.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.24`, title is `0.6.24`

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you check this one, please?

**Comment by yegor256** [comment]
@volodya-lombrozo works fine, thanks!
