### ISSUE TITLE
replace jeo.string with org.eolang.string

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#920]
Now, this is what I see in XMIR:

```
<o base="jeo.string"><!-- "java/lang/Object" -->
  <o base="org.eolang.bytes">6A-61-76-61-2F-6C-61-6E-67-2F-4F-62-6A-65-63-74</o>
</o>
```

Why not this?:

```
<o base="org.eolang.string"><!-- "java/lang/Object" -->
  <o base="org.eolang.bytes">6A-61-76-61-2F-6C-61-6E-67-2F-4F-62-6A-65-63-74</o>
</o>
```

Switching to `org.eolang.string` will help us use syntax sugar, thus making phi expressions much more readable.

The same it true about `jeo.int`, which may be replaced with `org.eolang.number` (however, pay attention, that we use float here, not integer!).

**Comment by yegor256** [comment]
@volodya-lombrozo now, this is a phi expression (for example):

```
              aff4384f-cf80-42d8-9031-8793d006f592 ↦ Φ.jeo.seq.of3 (
                α0 ↦ Φ.jeo.string (
                  α0 ↦ Φ.org.eolang.bytes (
                    α0 ↦ ⟦
                      Δ ⤍ 6A-61-76-61-2F-75-74-69-6C-2F-66-75-6E-63-74-69-6F-6E-2F-4C-6F-6E-67-55-6E-61-72-79-4F-70-65-72-61-74-6F-72
                    ⟧
                  )
                ),
                α1 ↦ Φ.jeo.int (
                  α0 ↦ Φ.org.eolang.bytes (
                    α0 ↦ ⟦
                      Δ ⤍ 00-00-00-00-00-00-00-04
                    ⟧
                  )
                ),
                α2 ↦ Φ.jeo.int (
                  α0 ↦ Φ.org.eolang.bytes (
                    α0 ↦ ⟦
                      Δ ⤍ 00-00-00-00-00-00-00-01
                    ⟧
                  )
                )
              ),

```

After the changes suggested, it will look like this:

```
              aff4384f-cf80-42d8-9031-8793d006f592 ↦ Φ.jeo.seq.of3 (
                α0 ↦ "hello, world...",
                α1 ↦ 4,
                α2 ↦ 1
              ),

```

The difference is obvious.

**Comment by volodya-lombrozo** [comment]
Progress is blocked due to the absence of documentation.

**Comment by yegor256** [comment]
@volodya-lombrozo our `number` is exactly the same as Number in JS: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number

**Comment by volodya-lombrozo** [comment]
@yegor256 Then it's impossible to use it. I won't be able to restore the type.

**Comment by volodya-lombrozo** [comment]
@yegor256  I can try to wrap all `eo` numbers with specific types:

```
jeo.int (
  org.eolang.number (
    org.eolang.bytes (
       α0 ↦ ⟦
          Δ ⤍ 00-00-00-00-00-00-00-01
        ⟧
      )
   )
)
```
Will it help?

**Comment by yegor256** [comment]
@volodya-lombrozo `int` in Java is 4 bytes, while `number` in EO is 8 bytes. Maybe you can fit in?

**Comment by volodya-lombrozo** [comment]
@yegor256 I need to understand whether the `00-00-00-00-00-00-00-01` value is `1L` or `1`.

**Comment by yegor256** [comment]
@volodya-lombrozo neither :) `1` in EO would be represented as `3F-F0-00-00-00-00-00-00`

**Comment by volodya-lombrozo** [comment]
@yegor256 What about this: https://github.com/objectionary/jeo-maven-plugin/issues/920#issuecomment-2507681446 ?

**Comment by yegor256** [comment]
@volodya-lombrozo this will help a bit, but still the output will be pretty noisy. It's better to use `org.eolang.*` objects, which will lead to most compact representation in phi

**Comment by volodya-lombrozo** [comment]
@yegor256 I use `org.eolang.bytes` already :)  I can implement `org.eolang.string` for now. For the `org.eolang.number` I suggest to create another issue. What do you think?

**Comment by volodya-lombrozo** [comment]
@yegor256 Good then. In this issue I only replace `jeo.string` with `org.eolang.string`

**Comment by volodya-lombrozo** [comment]
@yegor256 Should I mention `org.eolang.string` in the `alias` section?

**Comment by yegor256** [comment]
@volodya-lombrozo nope, all objects that are inside `org.eolang` package are available by default (no need to use `+alias`)

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.25`, title is `0.6.25`

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you try the new version, please?

**Comment by yegor256** [comment]
@volodya-lombrozo works, thanks!
