### ISSUE TITLE
`eo-maven-plugin:print` fails with `java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#928]
[One of the recent builds](https://github.com/objectionary/jeo-maven-plugin/actions/runs/12115416372/job/33773728488?pr=927) failed with the following exception:
```
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.44.0:print (convert-xmir-to-eo) on project jeo-it: 'PrintMojo' execution failed: java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer; -> [Help 1]
```

You can find full logs here:
[build.log.txt](https://github.com/user-attachments/files/17975188/build.log.txt)

It's not a bug in `jeo-maven-plugin`, but influence it significantly.

**Comment by volodya-lombrozo** [comment]
`eo-maven-plugin` [states](https://github.com/objectionary/eo?tab=readme-ov-file#how-to-contribute) that I need Java 8 installed:

```
You will need [Maven 3.3+](https://maven.apache.org/) and Java 8+ installed.
```

But the goal fails exactly on Java 8. Maybe there are some inconsistencies between real code and the documentation.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please? It blocks entire development process in the `jeo-maven-plugin`.

**Comment by yegor256** [comment]
@volodya-lombrozo we support Java 11, I made the changes to the doc and our pom: https://github.com/objectionary/eo/issues/3589

**Comment by volodya-lombrozo** [comment]
@yegor256 Thank you for the clarification and the fix
