### ISSUE TITLE
testing of generated XMIR is not using our "lints"

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#938]
I suggest using `org.eolang:lints` library (https://github.com/objectionary/lints), which may help JEO validate all XMIR documents generated, for their validity:

```
import com.jcabi.xml.StrictXML;
import org.eolang.lints.Program;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

final class Foo {
  @Test
  void testValidProgram() {
    Assertions.assertTrue(
      new Program(
        new StrictXML("<program/>")
      ).defects().empty()
    );
  }
}
```

This way, you will be assured that XMIR is generated strictly by the rules.

**Comment by yegor256** [comment]
@volodya-lombrozo please, check

**Comment by volodya-lombrozo** [comment]
@yegor256 It's a good thing actually. Thank you. I will try.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help me with `objectionary/lints` usage please? I'm confused with all the new abstractions over `xmir` checking. 

What should I use to verify the generated `xmir`:

```java
new StrictXmir(res).inner()
```
or

```java
new Program(new StrictXmir(res)).defects()
```

or
```java
new Program(new StrictXML(res)).defects()
```
?

**Comment by yegor256** [comment]
@volodya-lombrozo while all three are valid, this would be the best choice:

```
new Program(new StrictXmir(res)).defects()
```

This way you will:

1) detect XSD errors
2) detect linting defects
3) avoid network interations, as much as it's possible

**Comment by volodya-lombrozo** [comment]
@yegor256 Thank you. Understood.

**Comment by volodya-lombrozo** [comment]
@yegor256 Still an issue? `objectionary/lints` was incorporated into the plugin starting from `0.7.0` version.

**Comment by yegor256** [comment]
@volodya-lombrozo perfect!
