### ISSUE TITLE
Try to Use `XML` Document From `jcabi-xml`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#948]
We used to use it before because it's rather simple, however had several performance issues. It's better to reuse it again. If we face any performance issues, it's better to fix them in `jcabi-xml`. Moreover, it makes sense to create a separate interface that would hide all the work with XML. By doing this we will be able easily switch between two implementations.

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#953](https://github.com/objectionary/jeo-maven-plugin/issues/953) is still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo the only puzzle [#953](https://github.com/objectionary/jeo-maven-plugin/issues/953) is solved here.

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for submitting this ticket! However, as you see, it was not accepted by the team, which is sad. You've earned -16 points. By reporting bugs or suggesting enhacements, you help our project improve its quality. Please, don't be discouraged. Instead, try to be more careful next time, and [do not hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) bugs. Your running balance is [+6](https://www.eolang.org/zerocracy/objectionary-vitals.html).
