### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/jeo-maven-plugin#949]
Due recent problems with updating `eo` we lost several dependency updates. Check the PRs created by renovate https://github.com/objectionary/jeo-maven-plugin/pulls. We need to update all these deps.

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for submitting this ticket! However, as you see, it was not accepted by the team, which is sad. You've earned -16 points. By reporting bugs or suggesting enhacements, you help our project improve its quality. Please, don't be discouraged. Instead, try to be more careful next time, and [do not hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) bugs. Your running balance is [+12](https://www.eolang.org/zerocracy/objectionary-vitals.html).
